version: "3"
services:
  api:
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "3006:3006"
    command: "yarn start"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    depends_on: 
    - postgres
    volumes:
      - .:/usr/app

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=transactions_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5442
      - POSTGRES_HOST=localhost
      - NODE_ENV=development
    user: postgres
    volumes:
      - database:/var/lib/postgresql/data
      - ./api/src/infrasctructure/interface/database:/docker-entrypoint-initdb.d/
    command: -p 5442
volumes:
  database: